### ISSUE TITLE
Client configuration - RFC

### ISSUE THREAD

**Issue by d21d3q** [the-maldridge/locksmith#10]
I have some suggestions in terms of obtaining client configuration

[Have a look](https://gist.github.com/oskar456/594f1b5e84ca887c439fb457800b377e) at how Couldflares WARP works - you obtain configuration from one endpoint, but you connect to another host. This would allow for having (in future) multiple `keyhole` servers. Something like https://pritunl.com/ uses - you have single web interface for management (and obtaining configuration), but you might have multiple VPN (keyhole) servers.

Another thing is way of obtaining configuration, which would address IoT (or machines in general). Imagine that you are provisioning some device which require VPN, so you just write config file with api url and token (given for lifetime), maybe interface name to use (`wg0`). All the work is done by backend - finding out which device is that. JWT is menat to be expirable, and might be invalidated if you change server secret (what would not be the case in tokens tied to device (client))

**Comment by the-maldridge** [comment]
You have described how locksmith is architected.  There is one locksmith server controlling an arbitrarily many number of keyholes, and configuration is requested via an authenticated API token.
